version: '3.9'
services:
  redis-sentinel:
    image: redis:7-alpine
    ports:
      - "26379:26379"
    container_name: redis-sentinel
    hostname: redis-sentinel
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./redis/sentinel.conf:/etc/sentinel.conf"
    networks:
      - koinz-network
    restart: always
    depends_on: [redis-master]
  redis-master:
    container_name: redis-master
    hostname: redis-master
    image: redis:7-alpine
    environment: {}
    networks:
      - aqarmap-network
    restart: always
networks:
  koinz-network:
    external: true
    name: ${NETWORK_NAME}
