version: "3.9"
services:
  mailcatcher:
    image: dockage/mailcatcher
    container_name: aqarmap-mailcatcher
    hostname: mailcatcher
    networks:
      - koinz-network
    environment: {}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailcatcher.rule=Host(`mailcatcher.koinz.local`)"
      - "traefik.http.routers.mailcatcher.entrypoints=web"
      - traefik.http.services.mailcatcher.loadbalancer.server.port=1080
networks:
  koinz-network:
    external: true
    name: ${NETWORK_NAME}
