version: '3.9'
services:
  mysql8:
    container_name: mysql8
    hostname: mysql8
    image: mysql:8
#    ports:
#      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=moonshot
      - MYSQL_USER=moonshot
      - MYSQL_DATABASE=moonshot
    networks:
      - koinz-network
    restart: always
networks:
  koinz-network:
    external: true
    name: ${NETWORK_NAME}
